# Generated by Django 6.1 on 2026-08-30 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0003_sessaocaixa_nome_operador'),
        ('clientes', '0001_initial'),
        ('empresas', '0002_empresa_cidade_empresa_cor_destaque_and_more'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.UniqueConstraint(condition=models.Q(('offline_uuid', ''), _negated=True), fields=('empresa', 'offline_uuid'), name='unique_empresa_offline_uuid'),
        ),
    ]
