# Generated by Django 6.1 on 2026-08-31 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_unique_empresa_offline_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Cancelamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
