# Generated by Django 6.1 on 2026-08-31 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_cidade_empresa_cor_destaque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('VENDA_CRIADA', 'Venda Criada'), ('VENDA_CANCELADA', 'Venda Cancelada'), ('DESCONTO_APLICADO', 'Desconto Aplicado'), ('CAIXA_ABERTO', 'Caixa Aberto'), ('CAIXA_FECHADO', 'Caixa Fechado'), ('SUPRIMENTO', 'Suprimento'), ('SANGRIA', 'Sangria'), ('DESPESA_CAIXA', 'Despesa Caixa'), ('AJUSTE_ESTOQUE', 'Ajuste de Estoque'), ('COMPRA_REGISTRADA', 'Compra Registrada'), ('FINANCEIRO_OPERACAO', 'Operação Financeira'), ('USUARIO_ALTERADO', 'Usuário Alterado'), ('PRODUTO_ALTERADO', 'Produto Alterado')], max_length=30, verbose_name='Ação')),
                ('entidade', models.CharField(help_text='Ex: Venda, Produto, SessaoCaixa', max_length=80, verbose_name='Entidade')),
                ('entidade_id', models.CharField(blank=True, max_length=50, verbose_name='ID da Entidade')),
                ('descricao', models.TextField(verbose_name='Descrição da Operação')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict, verbose_name='Dados Anteriores')),
                ('dados_posteriores', models.JSONField(blank=True, default=dict, verbose_name='Dados Posteriores')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='empresas.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
