# Generated by Django 6.1 on 2026-08-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(choices=[('VENDA_CRIADA', 'Venda Criada'), ('VENDA_CANCELADA', 'Venda Cancelada'), ('DESCONTO_APLICADO', 'Desconto Aplicado'), ('CAIXA_ABERTO', 'Caixa Aberto'), ('CAIXA_FECHADO', 'Caixa Fechado'), ('SUPRIMENTO', 'Suprimento'), ('SANGRIA', 'Sangria'), ('DESPESA_CAIXA', 'Despesa Caixa'), ('AJUSTE_ESTOQUE', 'Ajuste de Estoque'), ('COMPRA_REGISTRADA', 'Compra Registrada'), ('FINANCEIRO_OPERACAO', 'Operação Financeira'), ('USUARIO_ALTERADO', 'Usuário Alterado'), ('PRODUTO_ALTERADO', 'Produto Alterado'), ('CLIENTE_CRIADO', 'Cliente Criado'), ('CLIENTE_ALTERADO', 'Cliente Alterado'), ('CREDIARIO_CONCEDIDO', 'Crediário Concedido'), ('CONTA_RECEBER_CRIADA', 'Conta a Receber Criada'), ('RECEBIMENTO_REGISTRADO', 'Recebimento Registrado'), ('RECEBIMENTO_CANCELADO', 'Recebimento Cancelado'), ('LIMITE_CREDITO_ALTERADO', 'Limite de Crédito Alterado'), ('IMPORTACAO_DADOS', 'Importação de Dados'), ('CONFIGURACAO_VISUAL_ALTERADA', 'Configuração Visual Alterada')], max_length=30, verbose_name='Ação'),
        ),
    ]
