# Generated by Django 6.1 on 2026-09-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_options_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='condicao_pagamento_padrao',
            field=models.CharField(choices=[('A_VISTA', 'À vista (0 dias)'), ('1_DIA', 'Boleto 1 dia'), ('2_DIAS', 'Boleto 2 dias'), ('3_DIAS', 'Boleto 3 dias'), ('4_DIAS', 'Boleto 4 dias'), ('7_DIAS', 'Boleto 7 dias'), ('14_DIAS', 'Boleto 14 dias'), ('21_DIAS', 'Boleto 21 dias'), ('28_DIAS', 'Boleto 28 dias'), ('30_DIAS', 'Boleto 30 dias'), ('PERSONALIZADO', 'Personalizado (dias informados)')], default='30_DIAS', max_length=30, verbose_name='Condição de Pagamento Padrão'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazo_pagamento_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Prazo Padrão (dias)'),
        ),
    ]
