# Generated by Django 6.1 on 2026-08-30 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0004_alter_movimentacaocaixa_tipo_and_more'),
        ('empresas', '0002_empresa_cidade_empresa_cor_destaque_and_more'),
        ('financeiro', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['data_vencimento', '-id'], 'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AlterModelOptions(
            name='contareceber',
            options={'ordering': ['data_vencimento', '-id'], 'verbose_name': 'Conta a Receber', 'verbose_name_plural': 'Contas a Receber'},
        ),
        migrations.AlterModelOptions(
            name='fluxocaixa',
            options={'ordering': ['-data_movimento'], 'verbose_name': 'Fluxo de Caixa', 'verbose_name_plural': 'Fluxos de Caixa'},
        ),
        migrations.AddField(
            model_name='contareceber',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Original Histórico (R$)'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Pago (R$)'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Quitação'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('PARCIAL', 'Parcial'), ('QUITADA', 'Quitada'), ('CANCELADA', 'Cancelada'), ('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='ABERTA', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Original (R$)'),
        ),
        migrations.CreateModel(
            name='PagamentoContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Recebido (R$)')),
                ('troco', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Troco (R$)')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão Débito'), ('CARTAO_CREDITO', 'Cartão Crédito')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_recebidos', to='financeiro.contareceber')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('sessao_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_crediario', to='caixas.sessaocaixa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de Conta a Receber',
                'verbose_name_plural': 'Pagamentos de Contas a Receber',
                'ordering': ['-data_hora'],
            },
        ),
    ]
