# Generated by Django 6.1 on 2026-08-30 23:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0004_alter_movimentacaocaixa_tipo_and_more'),
        ('clientes', '0003_alter_cliente_options_alter_fornecedor_options_and_more'),
        ('empresas', '0002_empresa_cidade_empresa_cor_destaque_and_more'),
        ('financeiro', '0003_alter_contapagar_options_alter_contareceber_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['data_vencimento', '-id'], 'verbose_name': 'Conta a Pagar / Despesa', 'verbose_name_plural': 'Contas a Pagar / Despesas'},
        ),
        migrations.AddField(
            model_name='contapagar',
            name='data_competencia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Despesa / Competência'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=20, verbose_name='Forma de Pagamento Principal'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='recorrente_competencia',
            field=models.CharField(blank=True, max_length=15, verbose_name='Competência (ex: 2026-09)'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='sessao_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_pagas', to='caixas.sessaocaixa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Original Histórico (R$)'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Pago (R$)'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('PARCIAL', 'Parcial'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada'), ('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='ABERTA', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Original (R$)'),
        ),
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='financeiro.categoriadespesa'),
        ),
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da Despesa Recorrente')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Fixo / Estimado (R$)')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('SEMANAL', 'Semanal'), ('ANUAL', 'Anual')], default='MENSAL', max_length=15, verbose_name='Periodicidade')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, verbose_name='Dia do Vencimento (1-31)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término (Opcional)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_recorrentes', to='financeiro.categoriadespesa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_recorrentes', to='clientes.fornecedor')),
            ],
            options={
                'verbose_name': 'Despesa Recorrente',
                'verbose_name_plural': 'Despesas Recorrentes',
                'ordering': ['dia_vencimento', 'descricao'],
            },
        ),
        migrations.AddField(
            model_name='contapagar',
            name='despesa_recorrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='financeiro.despesarecorrente'),
        ),
        migrations.CreateModel(
            name='PagamentoContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago (R$)')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro (Caixa Físico)'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão Débito'), ('CARTAO_CREDITO', 'Cartão Crédito'), ('BOLETO', 'Boleto Bancário'), ('TRANSFERENCIA', 'Transferência Bancária')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('conta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_detalhes', to='financeiro.contapagar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('sessao_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_despesas', to='caixas.sessaocaixa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_despesas_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de Despesa / Conta a Pagar',
                'verbose_name_plural': 'Pagamentos de Despesas / Contas a Pagar',
                'ordering': ['-data_hora'],
            },
        ),
    ]
