# Generated by Django 6.1 on 2026-09-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_contapagar_options_contapagar_data_competencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocontareceber',
            name='motivo_abatimento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo do Abatimento'),
        ),
        migrations.AddField(
            model_name='pagamentocontareceber',
            name='valor_abatimento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Abatimento (R$)'),
        ),
    ]
