# Generated by Django 6.1.1 on 2026-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_pagamentocontareceber_motivo_abatimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentocontapagar',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro (Caixa Físico)'), ('DINHEIRO_EXTERNO', 'Dinheiro Próprio (Fora do Caixa)'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão Débito'), ('CARTAO_CREDITO', 'Cartão Crédito'), ('BOLETO', 'Boleto Bancário'), ('TRANSFERENCIA', 'Transferência Bancária')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
