# Generated by Django 6.1 on 2026-08-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo_barras', models.CharField(db_index=True, max_length=50, verbose_name='Código de Barras (EAN)')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU / Código Interno')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Preço de Custo (R$)')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=30.0, help_text='Cálculo base: Venda = Custo / (1 - (Margem/100))', max_digits=6, verbose_name='Margem de Lucro Bruto (%)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Preço de Venda (R$)')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Estoque Mínimo')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade (UN)'), ('KG', 'Quilograma (KG)'), ('LT', 'Litro (LT)'), ('CX', 'Caixa (CX)'), ('PCT', 'Pacote (PCT)'), ('M2', 'Metro Quadrado (M²)')], default='UN', max_length=10, verbose_name='Unidade de Medida')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'unique_together': {('empresa', 'codigo_barras')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste Manual')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('preco_custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo Unitário (R$)')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('origem_ref', models.CharField(blank=True, max_length=100, verbose_name='Referência de Origem')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
            },
        ),
    ]
