# Generated by Django 5.1 on 2026-09-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='preco_custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Custo Unitário (R$)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Preço de Custo (R$)'),
        ),
    ]
