# Generated by Django 6.1 on 2026-08-30 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_fornecedor_endereco_fornecedor_observacoes'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='estoque_anterior',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Estoque Anterior'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='estoque_posterior',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Estoque Posterior'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='controle_estoque',
            field=models.BooleanField(default=True, verbose_name='Controla Estoque'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição / Detalhes'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_maximo',
            field=models.DecimalField(blank=True, decimal_places=3, default=1000.0, max_digits=12, null=True, verbose_name='Estoque Máximo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='clientes.fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste Manual'), ('ESTORNO', 'Estorno')], max_length=10, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='SKU / Código Interno'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade (UN)'), ('KG', 'Quilograma (KG)'), ('G', 'Grama (G)'), ('L', 'Litro (L)'), ('ML', 'Mililitro (ML)'), ('LT', 'Lata (LT)'), ('CX', 'Caixa (CX)'), ('PCT', 'Pacote (PCT)'), ('FD', 'Fardo (FD)'), ('M2', 'Metro Quadrado (M²)')], default='UN', max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
