# Generated by Django 6.1.1 on 2026-10-03 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_preco_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_produto_terceiro',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Produto de Terceiro'),
        ),
        migrations.AddField(
            model_name='produto',
            name='percentual_repasse',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('70.00'), max_digits=5, null=True, verbose_name='Percentual de Repasse (%)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='preco_custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Custo Unitário (R$)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Preço de Custo (R$)'),
        ),
    ]
