# Generated by Django 6.1 on 2026-08-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_destaque',
            field=models.CharField(default='#16a34a', max_length=20, verbose_name='Cor de Destaque'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_fundo_cabecalho',
            field=models.CharField(default='#dc2626', max_length=20, verbose_name='Cor Fundo Cabeçalho'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_fundo_geral',
            field=models.CharField(default='#f8fafc', max_length=20, verbose_name='Cor Fundo Geral'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_fundo_paineis',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Cor Fundo Painéis'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_texto_cabecalho',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Cor Texto Cabeçalho'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
