# Generated by Django 6.1 on 2026-08-31 20:45

import apps.empresas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cidade_empresa_cor_destaque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia_exibicao', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia Exibido')),
                ('subtitulo_cabecalho', models.CharField(blank=True, default='PDV Enterprise', max_length=200, verbose_name='Subtítulo do Cabeçalho')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_custom/', verbose_name='Logo Customizado')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Favicon')),
                ('cor_principal', models.CharField(default='#2563eb', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Principal')),
                ('cor_secundaria', models.CharField(default='#475569', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Secundária')),
                ('cor_destaque', models.CharField(default='#f59e0b', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor de Destaque')),
                ('cor_menu_sidebar', models.CharField(default='#0f172a', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Menu/Navbar')),
                ('cor_fundo', models.CharField(default='#f8fafc', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Plano de Fundo')),
                ('cor_cards', models.CharField(default='#ffffff', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor dos Cards')),
                ('cor_texto', models.CharField(default='#1e293b', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor do Texto')),
                ('cor_texto_secundario', models.CharField(default='#64748b', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Texto Secundário')),
                ('cor_botoes', models.CharField(default='#2563eb', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor dos Botões')),
                ('cor_botoes_acao', models.CharField(default='#10b981', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor dos Botões de Ação')),
                ('cor_links', models.CharField(default='#2563eb', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor dos Links')),
                ('cor_sucesso', models.CharField(default='#16a34a', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Sucesso')),
                ('cor_alerta', models.CharField(default='#d97706', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Alerta')),
                ('cor_erro', models.CharField(default='#dc2626', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Erro')),
                ('cor_pdv_fundo', models.CharField(default='#0f172a', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Fundo PDV')),
                ('cor_pdv_texto', models.CharField(default='#ffffff', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Texto PDV')),
                ('cor_pdv_preco', models.CharField(default='#22c55e', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor dos Preços')),
                ('cor_pdv_total', models.CharField(default='#eab308', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor do Total Geral')),
                ('cor_pdv_botao_finalizar', models.CharField(default='#16a34a', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Botão Finalizar')),
                ('cor_pdv_botao_cancelar', models.CharField(default='#dc2626', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Botão Cancelar')),
                ('cor_pdv_botoes_pagamento', models.CharField(default='#3b82f6', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Botões Pagamento')),
                ('tamanho_fonte_preco', models.CharField(default='1.25rem', max_length=20, verbose_name='Tamanho Fonte Preço')),
                ('tamanho_fonte_total', models.CharField(default='2.0rem', max_length=20, verbose_name='Tamanho Fonte Total')),
                ('tamanho_fonte_itens', models.CharField(default='1.0rem', max_length=20, verbose_name='Tamanho Fonte Itens')),
                ('modo_layout', models.CharField(choices=[('CONFORTAVEL', 'Confortável'), ('COMPACTO', 'Compacto')], default='CONFORTAVEL', max_length=20, verbose_name='Modo de Layout')),
                ('exibir_painel_produtos_rapidos', models.BooleanField(default=True, verbose_name='Exibir Produtos Rápidos no PDV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_visual', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Visual',
                'verbose_name_plural': 'Configurações Visuais',
            },
        ),
    ]
