# Generated by Django 6.1 on 2026-09-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_configuracaovisual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAtalhoPDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao_codigo', models.CharField(max_length=50, verbose_name='Código da Função')),
                ('tecla', models.CharField(max_length=20, verbose_name='Tecla de Atalho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atalhos_pdv', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Atalho do PDV',
                'verbose_name_plural': 'Atalhos do PDV',
                'unique_together': {('empresa', 'funcao_codigo'), ('empresa', 'tecla')},
            },
        ),
    ]
