# Generated by Django 6.1 on 2026-09-03 19:34

import apps.empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_configuracaoatalhopdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaovisual',
            name='cor_pdv_botao_divida',
            field=models.CharField(default='#7c3aed', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Botão Receber Dívida'),
        ),
        migrations.AddField(
            model_name='configuracaovisual',
            name='cor_pdv_botao_espera',
            field=models.CharField(default='#2563eb', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Botão Em Espera'),
        ),
        migrations.AddField(
            model_name='configuracaovisual',
            name='cor_pdv_botao_pausar',
            field=models.CharField(default='#d97706', max_length=7, validators=[apps.empresas.models.validar_hex_color], verbose_name='Cor Botão Pausar Venda'),
        ),
    ]
