# Generated by Django 6.1 on 2026-09-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_configuracaovisual_cor_pdv_botao_divida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Razão Social'),
        ),
    ]
