# Generated by Django 6.1 on 2026-09-12 14:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('empresas', '0006_alter_empresa_nome_fantasia_and_more'),
        ('produtos', '0002_alter_movimentacaoestoque_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-data_compra'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='quantidade_recebida',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Quantidade Recebida'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Recebimento'), ('PARCIAL', 'Recebimento Parcial'), ('CONCLUIDA', 'Concluída / Recebida'), ('CANCELADA', 'Cancelada'), ('RASCUNHO', 'Rascunho')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade Pedida'),
        ),
        migrations.CreateModel(
            name='RecebimentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_recebimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Recebimento')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação / NF Entrega')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='compras.compra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recebimento de Compra',
                'verbose_name_plural': 'Recebimentos de Compras',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecebimentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade Deste Recebimento')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Custo Unitário Praticado (R$)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('item_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='compras.itemcompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_recebidos_compras', to='produtos.produto')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.recebimentocompra')),
            ],
            options={
                'verbose_name': 'Item de Recebimento de Compra',
                'verbose_name_plural': 'Itens de Recebimento de Compra',
            },
        ),
    ]
