# Generated by Django 5.1 on 2026-09-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_options_itemcompra_quantidade_recebida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='preco_custo_unitario',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Custo Unitário (R$)'),
        ),
    ]
