# Generated by Django 6.1.1 on 2026-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_itemcompra_preco_custo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='preco_custo_unitario',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Custo Unitário (R$)'),
        ),
    ]
