# Generated by Django 6.1 on 2026-08-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora Abertura')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Inicial (R$)')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Fechamento')),
                ('saldo_final_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final Calculado (R$)')),
                ('saldo_final_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final Informado (R$)')),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferença (R$)')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações de Fechamento')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Caixa')),
                ('codigo_identificador', models.CharField(max_length=50, verbose_name='Código Identificador')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='FECHADO', max_length=10, verbose_name='Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('SUPRIMENTO', 'Suprimento (Aporte)'), ('SANGRIA', 'Sangria (Retirada)')], max_length=15, verbose_name='Tipo de Movimentação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo / Descrição')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
            },
        ),
    ]
