# Generated by Django 6.1 on 2026-08-30 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixas', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaocaixa',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='caixas.caixa'),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaocaixa',
            name='sessao_caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='caixas.sessaocaixa'),
        ),
        migrations.AlterUniqueTogether(
            name='caixa',
            unique_together={('empresa', 'codigo_identificador')},
        ),
    ]
