# Generated by Django 6.1 on 2026-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaocaixa',
            name='nome_operador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome / Apelido do Operador'),
        ),
    ]
