# Generated by Django 6.1 on 2026-08-30 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0003_sessaocaixa_nome_operador'),
        ('empresas', '0002_empresa_cidade_empresa_cor_destaque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='tipo',
            field=models.CharField(choices=[('SUPRIMENTO', 'Suprimento (Aporte)'), ('SANGRIA', 'Sangria (Retirada)'), ('DESPESA', 'Despesa Paga pelo Caixa'), ('ESTORNO', 'Estorno')], max_length=15, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ABERTA')), fields=('empresa', 'caixa'), name='unique_sessao_aberta_por_caixa'),
        ),
    ]
