# Generated by Django 6.1 on 2026-08-31 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_configuracaovisual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='Tamanho em Bytes')),
                ('hash_arquivo', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash SHA256 do Arquivo')),
                ('tipo_entidade', models.CharField(choices=[('PRODUTOS', 'Produtos'), ('CLIENTES', 'Clientes'), ('CATEGORIAS', 'Categorias'), ('FORNECEDORES', 'Fornecedores'), ('MISTO', 'Multi-Entidade / Estrutura Hierárquica')], default='PRODUTOS', max_length=50, verbose_name='Tipo de Entidade')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total de Registros')),
                ('quantidade_criada', models.IntegerField(default=0, verbose_name='Criados')),
                ('quantidade_atualizada', models.IntegerField(default=0, verbose_name='Atualizados')),
                ('quantidade_rejeitada', models.IntegerField(default=0, verbose_name='Rejeitados')),
                ('quantidade_ignorada', models.IntegerField(default=0, verbose_name='Ignorados')),
                ('mapeamento_utilizado', models.JSONField(blank=True, default=dict, verbose_name='Mapeamento de Campos Utilizado')),
                ('detalhes_erros', models.JSONField(blank=True, default=list, verbose_name='Relatório Detalhado de Erros')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado com Sucesso'), ('PROCESSADO_COM_ERROS', 'Processado com Erros'), ('FALHA', 'Falha Crítica')], default='PENDENTE', max_length=30, verbose_name='Status da Importação')),
                ('mensagem_status', models.TextField(blank=True, verbose_name='Mensagem de Status')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e Hora')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_importacoes', to='empresas.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Importação',
                'verbose_name_plural': 'Histórico de Importações',
                'ordering': ['-data_hora'],
            },
        ),
    ]
