# Generated by Django 6.1 on 2026-08-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='limite_desconto_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual máximo de desconto que este usuário pode aplicar (0 = sem limite definido).', max_digits=5, verbose_name='Limite de Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('OPERADOR', 'Operador de Caixa'), ('ESTOQUISTA', 'Estoquista'), ('FINANCEIRO', 'Financeiro')], default='OPERADOR', max_length=20, verbose_name='Cargo'),
        ),
    ]
